# Generated by Django 3.0 on 2020-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Shirt', 'S')], max_length=200),
        ),
        migrations.AlterField(
            model_name='requiredproduct',
            name='catagory',
            field=models.CharField(choices=[('Shirt', 'S')], max_length=30),
        ),
    ]
