# Generated by Django 3.0 on 2020-07-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200718_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='93911', max_length=255),
        ),
    ]
