# Generated by Django 3.0 on 2020-07-02 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200702_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='catagory',
            field=models.ForeignKey(choices=[('Shirt', 'S')], on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
