# Generated by Django 3.0 on 2020-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200718_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='15242', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
