# Generated by Django 3.0 on 2020-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200713_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='Text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='28381', max_length=20),
        ),
    ]
