# Generated by Django 3.0 on 2020-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200714_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='97621', max_length=20),
        ),
        migrations.AlterField(
            model_name='requiredproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='required/%Y/%m/%d'),
        ),
    ]
