# Generated by Django 3.0 on 2020-07-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200714_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='32462', max_length=20),
        ),
        migrations.AlterField(
            model_name='requiredproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
