# Generated by Django 3.0 on 2020-07-15 03:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200714_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='billing_address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_address',
            name='region',
            field=models.CharField(default='Asia', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='26711', max_length=20),
        ),
    ]
