# Generated by Django 3.0 on 2020-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200717_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='last_name',
        ),
        migrations.AddField(
            model_name='billing_address',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='58001', max_length=20),
        ),
    ]
