# Generated by Django 3.0 on 2020-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200719_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.TextField(default='Here are the details about the item i want'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='orderitems/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='94253', max_length=255),
        ),
    ]
