# Generated by Django 3.0 on 2020-07-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200719_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='15234', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(upload_to='orderitems/'),
        ),
    ]
