# Generated by Django 3.0 on 2020-07-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='billing_address',
            name='region',
        ),
    ]
