# Generated by Django 3.0 on 2020-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200719_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('proof_image', models.ImageField(upload_to='proofs/')),
                ('proof_description', models.TextField()),
            ],
        ),
    ]
